name: Build and Upload to Tag

on:
  push:
    tags:
      - 'v*'  # 仅在以 v 开头的 tag 推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up CMake
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # Configure and build the project
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Upload the built artifacts
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/TestAction
          asset_name: TestAction
          asset_content_type: application/octet-stream

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
